---
- hosts: digitalocean
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install required packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Add Docker's official GPG key
      ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Setup stable Docker repository
      ansible.builtin.shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt cache
      apt: update_cache=yes

    - name: Install Docker
      apt: name=docker-ce state=present

    - name: Pull PairFair Docker image
      docker_image:
        name: peteralcock/pairfair
        source: pull

    - name: Run PairFair Docker container
      docker_container:
        name: pairfair
        image: peteralcock/pairfair
        state: started
        published_ports: 80:3000
